# -*- coding: utf-8 -*-
"""fake_news_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hGD0iyMhoixDbI2qNTEWuXqdspQVHgy4

# **Fake News Detection using NLP (Bag of N-grams)**
"""

import pandas as pd
import spacy
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

df=pd.read_csv('Fake_Real_Data.csv')
print(df.head())
print(df.label.value_counts())

nlp=spacy.load("en_core_web_sm")

def preprocess(text):
  doc=nlp(text)
  filtered_tokens=[]

  for token in doc:
    if token.is_stop or token.is_punct:
      continue
    filtered_tokens.append(token.lemma_)
  return ' '.join(filtered_tokens)

df['new_Text']=df.Text.apply(preprocess)
df.head(5)

print(len(df.loc[1,'Text']))
print(len(df.loc[1,'new_Text']))

X_train,X_test,y_train,y_test=train_test_split(df.new_Text,df.label,test_size=0.2, random_state=42,stratify=df.label)

print(y_train.value_counts())
print(y_test.value_counts())

"""## **Naive Bayes**"""

model1=Pipeline([
    ('cv',CountVectorizer(ngram_range=(1,2))),
    ('nb',MultinomialNB())
])

model1.fit(X_train,y_train)
y_pred=model1.predict(X_test)
report=classification_report(y_test,y_pred)
print(report)

"""## **Random Forest**"""

model2=Pipeline([
    ('cv',CountVectorizer(ngram_range=(1,2))),
    ('nb',RandomForestClassifier())
])

model2.fit(X_train,y_train)
y_pred=model2.predict(X_test)
report=classification_report(y_test,y_pred)
print(report)

"""## **Conclusion:**
### In this project, Multinomial Naive Bayes and Random Forest were trained on preprocessed text using Bag of n-grams (unigram and bigram). Both models performed well, with Random Forest achieving slightly higher accuracy and F1-score.
"""